### ISSUE TITLE
Returning nested/multidimensional arrays gives "incompatible value type"

### ISSUE THREAD

**Issue by jannschu** [pllua/pllua#14]
Hi,

I tried to return nested arrays:

```sql
create function test() returns int[] language pllua as $$
    return {{1,2},{3,4}}
$$;
select test();
```

But I get

```
ERROR:  pllua: incompatible value type
```

Is there a way to return such arrays?

**Comment by RhodiumToad** [comment]
yes, but currently to avoid ambiguity you need to give the dimensions:
```
  return {{1,2},{3,4}},2,2
```
will return a 2x2 array. The precise rules for what to return are given in the docs for `pgtype` (the return values for a function are just passed as parameters to the type constructor for the return type); notice that it says that arraytype(table) only allows one-dimensional arrays.

(I tried to make the obvious thing work when it came to type conversions, but unfortunately that turned out to be too ambiguous in some cases.)

**Comment by jannschu** [comment]
Thank you! Sorry, missed that in the documentation.
